### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by kerams** [toburger/Fable.ReactTransitionGroup#2]
Hey, thanks for the binding. Is there a Nuget package for this? I've only found https://www.nuget.org/packages/Fable.ReactTransitionGroup/0.1.0-alpha-001, which I assume is the old pre-split version.

**Comment by toburger** [comment]
Hi @kerams, sadly I have no idea on how to bundle a Fable package for NuGet and I'm not in charge of the package on NuGet.
@MangelMaxime and/or @alfonsogarciacaro were extremely kind to package and upload the package to NuGet, so maybe one of them could help to release the new version?

**Comment by toburger** [comment]
If it helps I am more than willing to transfer the repo to the fable-compiler organization.

**Comment by MangelMaxime** [comment]
@toburger The package is already configured for Fable.

I will send a PR for adding more info in the fsproj so we have a link from Nuget to your repository like that people can send issue/find documentation etc.

I will also explain how to push the package to Nuget and make you an owner if you are ok. As you have ownership on the Github repo it makes sense to me for you to be an owner on Nuget too.

**Comment by toburger** [comment]
Awesome! Thank you @MangelMaxime
